///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type

// COM UUID-s, names and progID
#define TYPELIB_UUID "BD54D9E4-49D9-459E-A367-3EFB2C3A100D"
#define TYPELIB_NAME "MGA Decorator TypeLibrary (SM_LEESA)"
#define COCLASS_UUID "98A0A255-4D2D-48CF-B00A-27B5D57E4719"
#define COCLASS_NAME "MGA Decorator CoClass (SM_LEESA)"
#define COCLASS_PROGID "MGA.Decorator.SM_LEESA"

#define COCLASS_UUID_EXPLODED1  0x98a0a255
#define COCLASS_UUID_EXPLODED2   0x4d2d
#define COCLASS_UUID_EXPLODED3   0x48cf
#define COCLASS_UUID_EXPLODED4   0xb0
#define COCLASS_UUID_EXPLODED5   0xa
#define COCLASS_UUID_EXPLODED6   0x27
#define COCLASS_UUID_EXPLODED7   0xb5
#define COCLASS_UUID_EXPLODED8   0xd5
#define COCLASS_UUID_EXPLODED9   0x7e
#define COCLASS_UUID_EXPLODED10  0x47
#define COCLASS_UUID_EXPLODED11  0x19


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "SM_LEESA"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "StateMachine (SM) Interpreter using LEESA"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "SM"


#define BON_ICON_SUPPORT

#define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
