
// -*- C++ -*-
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl IDLTEXTEDITOR_CORE
// ------------------------------
#ifndef IDLTEXTEDITOR_CORE_EXPORT_H
#define IDLTEXTEDITOR_CORE_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (IDLTEXTEDITOR_CORE_HAS_DLL)
#  define IDLTEXTEDITOR_CORE_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && IDLTEXTEDITOR_CORE_HAS_DLL */

#if !defined (IDLTEXTEDITOR_CORE_HAS_DLL)
#  define IDLTEXTEDITOR_CORE_HAS_DLL 1
#endif /* ! IDLTEXTEDITOR_CORE_HAS_DLL */

#if defined (IDLTEXTEDITOR_CORE_HAS_DLL) && (IDLTEXTEDITOR_CORE_HAS_DLL == 1)
#  if defined (IDLTEXTEDITOR_CORE_BUILD_DLL)
#    define IDLTEXTEDITOR_CORE_Export ACE_Proper_Export_Flag
#    define IDLTEXTEDITOR_CORE_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define IDLTEXTEDITOR_CORE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* IDLTEXTEDITOR_CORE_BUILD_DLL */
#    define IDLTEXTEDITOR_CORE_Export ACE_Proper_Import_Flag
#    define IDLTEXTEDITOR_CORE_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define IDLTEXTEDITOR_CORE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* IDLTEXTEDITOR_CORE_BUILD_DLL */
#else /* IDLTEXTEDITOR_CORE_HAS_DLL == 1 */
#  define IDLTEXTEDITOR_CORE_Export
#  define IDLTEXTEDITOR_CORE_SINGLETON_DECLARATION(T)
#  define IDLTEXTEDITOR_CORE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* IDLTEXTEDITOR_CORE_HAS_DLL == 1 */

// Set IDLTEXTEDITOR_CORE_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (IDLTEXTEDITOR_CORE_NTRACE)
#  if (ACE_NTRACE == 1)
#    define IDLTEXTEDITOR_CORE_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define IDLTEXTEDITOR_CORE_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !IDLTEXTEDITOR_CORE_NTRACE */

#if (IDLTEXTEDITOR_CORE_NTRACE == 1)
#  define IDLTEXTEDITOR_CORE_TRACE(X)
#else /* (IDLTEXTEDITOR_CORE_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define IDLTEXTEDITOR_CORE_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (IDLTEXTEDITOR_CORE_NTRACE == 1) */

#endif /* IDLTEXTEDITOR_CORE_EXPORT_H */

// End of auto generated file.
