/* Hello.h
   Generated by wsdl2h 1.2.8c from Hello.wsdl and typemap.dat
   2007-07-18 23:47:08 GMT
   Copyright (C) 2001-2006 Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control schema namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.
 - Use wsdl2h option -l to view the software license terms.

   DO NOT include this file directly into your project.
   Include only the soapcpp2-generated headers and source code files.
*/

//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * urn:Hello                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

Hello = "urn:Hello"
CORBA = "http://www.omg.org/IDL-WSDL/1.0/"

*/

//gsoap Hello schema namespace:	urn:Hello
//gsoap CORBA schema namespace:	http://www.omg.org/IDL-WSDL/1.0/
//gsoap Hello schema form:	unqualified
//gsoap CORBA schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Schema Types                                                               *
 *                                                                            *
\******************************************************************************/

class xsd__anyType { _XML __item; struct soap *soap; };

/// Primitive built-in type "xs:ID"
typedef char* xsd__ID;

/// Class wrapper for built-in type "xs:ID" derived from xsd__anyType
class xsd__ID_ : public xsd__anyType
{ public:
    xsd__ID                              __item;                    
};

/// Primitive built-in type "xs:anyURI"
typedef char* xsd__anyURI;

/// Class wrapper for built-in type "xs:anyURI" derived from xsd__anyType
class xsd__anyURI_ : public xsd__anyType
{ public:
    xsd__anyURI                          __item;                    
};

/// Class wrapper for built-in type "xs:int" derived from xsd__anyType
class xsd__int : public xsd__anyType
{ public:
    int                                  __item;                    
};

/// Class wrapper for built-in type "xs:string" derived from xsd__anyType
class xsd__string : public xsd__anyType
{ public:
    char*                                __item;                    
};

/// Class wrapper for built-in type "xs:unsignedInt" derived from xsd__anyType
class xsd__unsignedInt : public xsd__anyType
{ public:
    unsigned int                         __item;                    
};


//  Forward declaration of class Hello__Hello_x002eTimeOut.
class Hello__Hello_x002eTimeOut;

//  Forward declaration of class CORBA__ObjectReference.
class CORBA__ObjectReference;

//  Forward declaration of class CORBA__CORBA_x002eTypeCode.
class CORBA__CORBA_x002eTypeCode;

//  Forward declaration of class CORBA__CORBA_x002eAny.
class CORBA__CORBA_x002eAny;

//  Forward declaration of class CORBA__CORBA_x002eSystemException.
class CORBA__CORBA_x002eSystemException;

//  Forward declaration of class _CORBA__SourceIDL.
class _CORBA__SourceIDL;

//  Forward declaration of class _CORBA__SourceRepositoryID.
class _CORBA__SourceRepositoryID;

/// "urn:Hello":Hello.COLOR_SELECTION is a simpleType restriction of xs:string.
/// Note: enum values are prefixed with 'Hello__Hello_x002eCOLOR_USCORESELECTION' to avoid name clashes, please use wsdl2h option -e to omit this prefix
enum Hello__Hello_x002eCOLOR_USCORESELECTION
{
	Hello__Hello_x002eCOLOR_USCORESELECTION__empty,	///< xs:string value="empty"
	Hello__Hello_x002eCOLOR_USCORESELECTION__white,	///< xs:string value="white"
	Hello__Hello_x002eCOLOR_USCORESELECTION__red,	///< xs:string value="red"
	Hello__Hello_x002eCOLOR_USCORESELECTION__yellow,	///< xs:string value="yellow"
};

/// Class wrapper
class Hello__Hello_x002eCOLOR_USCORESELECTION_ : public xsd__anyType
{ public:
    enum Hello__Hello_x002eCOLOR_USCORESELECTION  __item;                    
};

/// "http://www.omg.org/IDL-WSDL/1.0/":CORBA.completion_status is a simpleType restriction of xs:string.
/// Note: enum values are prefixed with 'CORBA__CORBA_x002ecompletion_USCOREstatus' to avoid name clashes, please use wsdl2h option -e to omit this prefix
enum CORBA__CORBA_x002ecompletion_USCOREstatus
{
	CORBA__CORBA_x002ecompletion_USCOREstatus__COMPLETED_USCOREYES,	///< xs:string value="COMPLETED_YES"
	CORBA__CORBA_x002ecompletion_USCOREstatus__COMPLETED_USCORENO,	///< xs:string value="COMPLETED_NO"
	CORBA__CORBA_x002ecompletion_USCOREstatus__COMPLETED_USCOREMAYBE,	///< xs:string value="COMPLETED_MAYBE"
};

/// Class wrapper
class CORBA__CORBA_x002ecompletion_USCOREstatus_ : public xsd__anyType
{ public:
    enum CORBA__CORBA_x002ecompletion_USCOREstatus  __item;                    
};

/// "urn:Hello":Hello.TimeOut is a complexType.
class Hello__Hello_x002eTimeOut : public xsd__anyType
{ public:
/// Element data of type xs:string.
    char*                                data                           1;	///< Nullable pointer.
/// Attribute id of type xs:ID.
   @xsd__ID                              id                             0;	///< Optional attribute.
};

/// "http://www.omg.org/IDL-WSDL/1.0/":ObjectReference is a complexType.
class CORBA__ObjectReference : public xsd__anyType
{ public:
/// Size of array of xsd__anyURI is 1..unbounded
    int                                  __sizeurl                     ;
/// Pointer to array of length 1..unbounded
    xsd__anyURI                         *url                            1;
};

/// "http://www.omg.org/IDL-WSDL/1.0/":CORBA.TypeCode is a complexType.
class CORBA__CORBA_x002eTypeCode : public xsd__anyType
{ public:
/// Element definition of type xs:anyURI.
    xsd__anyURI                          definition                     1;	///< Required element.
/// Element typename of type xs:string.
    char*                                typename_                      1;	///< Required element.
};

/// "http://www.omg.org/IDL-WSDL/1.0/":CORBA.Any is a complexType.
class CORBA__CORBA_x002eAny : public xsd__anyType
{ public:
/// Element type of type "http://www.omg.org/IDL-WSDL/1.0/":CORBA.TypeCode.
    CORBA__CORBA_x002eTypeCode*          type                           1;	///< Required element.
/// Element value of type xs:anyType.
    xsd__anyType*                        value                          1;	///< Required element.
};

/// "http://www.omg.org/IDL-WSDL/1.0/":CORBA.SystemException is a complexType.
class CORBA__CORBA_x002eSystemException : public xsd__anyType
{ public:
/// Element minor of type xs:unsignedInt.
    unsigned int                         minor                          1;	///< Required element.
/// Element completion_status of type "http://www.omg.org/IDL-WSDL/1.0/":CORBA.completion_status.
    enum CORBA__CORBA_x002ecompletion_USCOREstatus  completion_USCOREstatus        1;	///< Required element.
};


/// Element "http://www.omg.org/IDL-WSDL/1.0/":SourceIDL of complexType.
/// @brief IDL/WSDL Mapping Info

/// "http://www.omg.org/IDL-WSDL/1.0/":SourceIDL is a complexType.
class _CORBA__SourceIDL
{ public:
/// Element source of type xs:string.
    char*                                source                         1;	///< Required element.
/// Element version of type xs:string.
    char*                                version                        1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://www.omg.org/IDL-WSDL/1.0/":SourceRepositoryID of complexType.
/// @brief IDL Mapped Repository ID

/// "http://www.omg.org/IDL-WSDL/1.0/":SourceRepositoryID is a complexType.
class _CORBA__SourceRepositoryID
{ public:
/// Element repositoryID of type xs:string.
    char*                                repositoryID                   1;	///< Required element.
/// Element version of type xs:string.
    char*                                version                        1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap Hello service name:	Hello_x002eSender
//gsoap Hello service type:	Hello_x002eReadMessage
//gsoap Hello service port:	http://localhost/Hello/Hello.asmx
//gsoap Hello service namespace:	urn:Hello
//gsoap Hello service transport:	http://schemas.xmlsoap.org/soap/http

/** @mainpage Hello Definitions

@section Hello_bindings Bindings
  - @ref Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage

*/

/**

@page Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage Binding "Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage"

@section Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage_operations Operations of Binding  "Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage"
  - @ref Hello__get_USCOREmessage
  - @ref Hello__start
  - @ref Hello___USCOREset_USCOREcolor
  - @ref Hello___USCOREget_USCOREcolor
  - @ref Hello___USCOREget_USCOREhertz
  - @ref Hello___USCOREset_USCORElocal_USCOREmessage
  - @ref Hello___USCOREget_USCORElocal_USCOREmessage

@section Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage_ports Endpoints of Binding  "Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage"
  - http://localhost/Hello/Hello.asmx

*/

/******************************************************************************\
 *                                                                            *
 * SOAP Fault Detail                                                          *
 *                                                                            *
\******************************************************************************/

/// The SOAP Fault Detail element contains one of the following types serialized
/// in the __type and fault fields of the SOAP_ENV__Detail struct (see docs)
class _CORBA__CORBA_x002eSystemExceptionMessage
{ public:
    CORBA__CORBA_x002eSystemException*  _USCOREreturn;
    struct soap                         *soap                          ;
};

/******************************************************************************\
 *                                                                            *
 * Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Hello__get_USCOREmessage                                                   *
 *                                                                            *
\******************************************************************************/


/// Operation "Hello__get_USCOREmessage" of service binding "Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP Fault: _CORBA__CORBA_x002eSystemExceptionMessage

C stub function (defined in soapClient.c[pp] after running soapcpp2):
@code
  int soap_call_Hello__get_USCOREmessage(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    // response parameters:
    char*                              &_USCOREreturn
  );
@endcode

C++ proxy class (defined in soapHello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessageProxy.h):
  class Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage;

*/

//gsoap Hello service method-style:	get_USCOREmessage rpc
//gsoap Hello service method-encoding:	get_USCOREmessage http://schemas.xmlsoap.org/soap/encoding/
//gsoap Hello service method-action:	get_USCOREmessage ""
//gsoap Hello service method-fault:	get_USCOREmessage _CORBA__CORBA_x002eSystemExceptionMessage
int Hello__get_USCOREmessage(
    char*                              &_USCOREreturn	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Hello__start                                                               *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "Hello__startResponse" of service binding "Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage" operation "Hello__start"
struct Hello__startResponse
{
};

/// Operation "Hello__start" of service binding "Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP Fault: _CORBA__CORBA_x002eSystemExceptionMessage

C stub function (defined in soapClient.c[pp] after running soapcpp2):
@code
  int soap_call_Hello__start(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    // response parameters:
    struct Hello__startResponse&
  );
@endcode

C++ proxy class (defined in soapHello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessageProxy.h):
  class Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage;

*/

//gsoap Hello service method-style:	start rpc
//gsoap Hello service method-encoding:	start http://schemas.xmlsoap.org/soap/encoding/
//gsoap Hello service method-action:	start ""
//gsoap Hello service method-fault:	start _CORBA__CORBA_x002eSystemExceptionMessage
int Hello__start(
    struct Hello__startResponse        &	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * Hello___USCOREset_USCOREcolor                                              *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "Hello___USCOREset_USCOREcolorResponse" of service binding "Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage" operation "Hello___USCOREset_USCOREcolor"
struct Hello___USCOREset_USCOREcolorResponse
{
};

/// Operation "Hello___USCOREset_USCOREcolor" of service binding "Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP Fault: _CORBA__CORBA_x002eSystemExceptionMessage

C stub function (defined in soapClient.c[pp] after running soapcpp2):
@code
  int soap_call_Hello___USCOREset_USCOREcolor(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    enum Hello__Hello_x002eCOLOR_USCORESELECTION value,
    // response parameters:
    struct Hello___USCOREset_USCOREcolorResponse&
  );
@endcode

C++ proxy class (defined in soapHello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessageProxy.h):
  class Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage;

*/

//gsoap Hello service method-style:	_USCOREset_USCOREcolor rpc
//gsoap Hello service method-encoding:	_USCOREset_USCOREcolor http://schemas.xmlsoap.org/soap/encoding/
//gsoap Hello service method-action:	_USCOREset_USCOREcolor ""
//gsoap Hello service method-fault:	_USCOREset_USCOREcolor _CORBA__CORBA_x002eSystemExceptionMessage
int Hello___USCOREset_USCOREcolor(
    enum Hello__Hello_x002eCOLOR_USCORESELECTION value,	///< Request parameter
    struct Hello___USCOREset_USCOREcolorResponse&	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * Hello___USCOREget_USCOREcolor                                              *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "Hello___USCOREget_USCOREcolorResponse" of service binding "Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage" operation "Hello___USCOREget_USCOREcolor"
struct Hello___USCOREget_USCOREcolorResponse
{
    enum Hello__Hello_x002eCOLOR_USCORESELECTION _USCOREreturn;
};

/// Operation "Hello___USCOREget_USCOREcolor" of service binding "Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP Fault: _CORBA__CORBA_x002eSystemExceptionMessage

C stub function (defined in soapClient.c[pp] after running soapcpp2):
@code
  int soap_call_Hello___USCOREget_USCOREcolor(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    // response parameters:
    struct Hello___USCOREget_USCOREcolorResponse&
  );
@endcode

C++ proxy class (defined in soapHello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessageProxy.h):
  class Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage;

*/

//gsoap Hello service method-style:	_USCOREget_USCOREcolor rpc
//gsoap Hello service method-encoding:	_USCOREget_USCOREcolor http://schemas.xmlsoap.org/soap/encoding/
//gsoap Hello service method-action:	_USCOREget_USCOREcolor ""
//gsoap Hello service method-fault:	_USCOREget_USCOREcolor _CORBA__CORBA_x002eSystemExceptionMessage
int Hello___USCOREget_USCOREcolor(
    struct Hello___USCOREget_USCOREcolorResponse&	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * Hello___USCOREget_USCOREhertz                                              *
 *                                                                            *
\******************************************************************************/


/// Operation "Hello___USCOREget_USCOREhertz" of service binding "Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP Fault: _CORBA__CORBA_x002eSystemExceptionMessage

C stub function (defined in soapClient.c[pp] after running soapcpp2):
@code
  int soap_call_Hello___USCOREget_USCOREhertz(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    // response parameters:
    int                                &_USCOREreturn
  );
@endcode

C++ proxy class (defined in soapHello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessageProxy.h):
  class Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage;

*/

//gsoap Hello service method-style:	_USCOREget_USCOREhertz rpc
//gsoap Hello service method-encoding:	_USCOREget_USCOREhertz http://schemas.xmlsoap.org/soap/encoding/
//gsoap Hello service method-action:	_USCOREget_USCOREhertz ""
//gsoap Hello service method-fault:	_USCOREget_USCOREhertz _CORBA__CORBA_x002eSystemExceptionMessage
int Hello___USCOREget_USCOREhertz(
    int                                &_USCOREreturn	///< Response parameter
);

/******************************************************************************\
 *                                                                            *
 * Hello___USCOREset_USCORElocal_USCOREmessage                                *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "Hello___USCOREset_USCORElocal_USCOREmessageResponse" of service binding "Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage" operation "Hello___USCOREset_USCORElocal_USCOREmessage"
struct Hello___USCOREset_USCORElocal_USCOREmessageResponse
{
};

/// Operation "Hello___USCOREset_USCORElocal_USCOREmessage" of service binding "Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP Fault: _CORBA__CORBA_x002eSystemExceptionMessage

C stub function (defined in soapClient.c[pp] after running soapcpp2):
@code
  int soap_call_Hello___USCOREset_USCORElocal_USCOREmessage(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               value,
    // response parameters:
    struct Hello___USCOREset_USCORElocal_USCOREmessageResponse&
  );
@endcode

C++ proxy class (defined in soapHello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessageProxy.h):
  class Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage;

*/

//gsoap Hello service method-style:	_USCOREset_USCORElocal_USCOREmessage rpc
//gsoap Hello service method-encoding:	_USCOREset_USCORElocal_USCOREmessage http://schemas.xmlsoap.org/soap/encoding/
//gsoap Hello service method-action:	_USCOREset_USCORElocal_USCOREmessage ""
//gsoap Hello service method-fault:	_USCOREset_USCORElocal_USCOREmessage _CORBA__CORBA_x002eSystemExceptionMessage
int Hello___USCOREset_USCORElocal_USCOREmessage(
    char*                               value,	///< Request parameter
    struct Hello___USCOREset_USCORElocal_USCOREmessageResponse&	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * Hello___USCOREget_USCORElocal_USCOREmessage                                *
 *                                                                            *
\******************************************************************************/


/// Operation "Hello___USCOREget_USCORElocal_USCOREmessage" of service binding "Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage"

/**

Operation details:

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP Fault: _CORBA__CORBA_x002eSystemExceptionMessage

C stub function (defined in soapClient.c[pp] after running soapcpp2):
@code
  int soap_call_Hello___USCOREget_USCORElocal_USCOREmessage(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    // response parameters:
    char*                              &_USCOREreturn
  );
@endcode

C++ proxy class (defined in soapHello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessageProxy.h):
  class Hello_x002eSender_x002e_USCORESE_USCOREpush_USCOREmessage;

*/

//gsoap Hello service method-style:	_USCOREget_USCORElocal_USCOREmessage rpc
//gsoap Hello service method-encoding:	_USCOREget_USCORElocal_USCOREmessage http://schemas.xmlsoap.org/soap/encoding/
//gsoap Hello service method-action:	_USCOREget_USCORElocal_USCOREmessage ""
//gsoap Hello service method-fault:	_USCOREget_USCORElocal_USCOREmessage _CORBA__CORBA_x002eSystemExceptionMessage
int Hello___USCOREget_USCORElocal_USCOREmessage(
    char*                              &_USCOREreturn	///< Response parameter
);

/* End of Hello.h */
