// -*- IDL -*-

#ifndef _DECORATORLIB_IDL_
#define _DECORATORLIB_IDL_

#include <Gme.idl>
#include <Core.idl>

[
  uuid (F32BA453-EA0A-4B33-972D-6BCE205891F8),
  version (1.0),
]
library ShowReferenceDecoratorLibrary
{
  importlib ("stdole32.tlb");
  importlib ("stdole2.tlb");

  [
    uuid (E3EA54FF-CE85-4F3B-92C4-6652FF130FE4),
  ]
  coclass ShowReferenceDecorator
  {
    [default] interface IMgaDecorator;
    interface IGMEVersionInfo;
  };

};

#endif
