// -*- IDL -*-

//=============================================================================
/**
 *  @file     ConnectorInstance_Decorator.idl
 *
 *  @author   James H. Hill
 */
//=============================================================================

#ifndef _PICML_CONNECTOR_INSTANCE_DECORATOR_IDL_
#define _PICML_CONNECTOR_INSTANCE_DECORATOR_IDL_

#include <Gme.idl>
#include <Core.idl>

[
  uuid (D91F2183-7728-4806-9593-283B0DD7605D),
  version (1.0),
]
library ConnectorInstance_DecoratorLib
{
  importlib ("stdole32.tlb");
  importlib ("stdole2.tlb");

  [
    uuid (EBC4DE1C-8C90-40C3-9C03-EF115D70D5BC),
    version (1.0)
  ]
  coclass ConnectorInstance_Decorator
  {
    [default] interface IMgaDecorator;
    interface IGMEVersionInfo;
  };

};

#endif
