
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl NOSHOWREFERSTO_DECORATOR
// ------------------------------
#ifndef NOSHOWREFERSTO_DECORATOR_EXPORT_H
#define NOSHOWREFERSTO_DECORATOR_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (NOSHOWREFERSTO_DECORATOR_HAS_DLL)
#  define NOSHOWREFERSTO_DECORATOR_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && NOSHOWREFERSTO_DECORATOR_HAS_DLL */

#if !defined (NOSHOWREFERSTO_DECORATOR_HAS_DLL)
#  define NOSHOWREFERSTO_DECORATOR_HAS_DLL 1
#endif /* ! NOSHOWREFERSTO_DECORATOR_HAS_DLL */

#if defined (NOSHOWREFERSTO_DECORATOR_HAS_DLL) && (NOSHOWREFERSTO_DECORATOR_HAS_DLL == 1)
#  if defined (NOSHOWREFERSTO_DECORATOR_BUILD_DLL)
#    define NOSHOWREFERSTO_DECORATOR_Export ACE_Proper_Export_Flag
#    define NOSHOWREFERSTO_DECORATOR_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define NOSHOWREFERSTO_DECORATOR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* NOSHOWREFERSTO_DECORATOR_BUILD_DLL */
#    define NOSHOWREFERSTO_DECORATOR_Export ACE_Proper_Import_Flag
#    define NOSHOWREFERSTO_DECORATOR_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define NOSHOWREFERSTO_DECORATOR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* NOSHOWREFERSTO_DECORATOR_BUILD_DLL */
#else /* NOSHOWREFERSTO_DECORATOR_HAS_DLL == 1 */
#  define NOSHOWREFERSTO_DECORATOR_Export
#  define NOSHOWREFERSTO_DECORATOR_SINGLETON_DECLARATION(T)
#  define NOSHOWREFERSTO_DECORATOR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* NOSHOWREFERSTO_DECORATOR_HAS_DLL == 1 */

// Set NOSHOWREFERSTO_DECORATOR_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (NOSHOWREFERSTO_DECORATOR_NTRACE)
#  if (ACE_NTRACE == 1)
#    define NOSHOWREFERSTO_DECORATOR_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define NOSHOWREFERSTO_DECORATOR_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !NOSHOWREFERSTO_DECORATOR_NTRACE */

#if (NOSHOWREFERSTO_DECORATOR_NTRACE == 1)
#  define NOSHOWREFERSTO_DECORATOR_TRACE(X)
#else /* (NOSHOWREFERSTO_DECORATOR_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define NOSHOWREFERSTO_DECORATOR_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (NOSHOWREFERSTO_DECORATOR_NTRACE == 1) */

#endif /* NOSHOWREFERSTO_DECORATOR_EXPORT_H */

// End of auto generated file.
