/*
 * @file: ConfiguratorDialog.h
 *
 * ConfiguratorDialog QT construction file
 *
 * Most of the file is generated by the QT resource compiler
 * 
 * @author: Emre Turkay <emre.turkay@vanderbilt.edu>
 */

#ifndef _CONFIGURATORDIALOG_H_
#define _CONFIGURATORDIALOG_H_

#include "options_view.h"
#include "help_view.h"
#include "category_list_view.h"
#include "options.h"

#include <qvariant.h>
#include <qdialog.h>
class QVBoxLayout; 
class QHBoxLayout; 
class QGridLayout; 
class QFrame;
class QListView;
class QListViewItem;
class QPushButton;
class QTextBrowser;

#include "rule_validator.h"

class ConfiguratorDialog : public QDialog
{ 
    Q_OBJECT

public:
    ConfiguratorDialog(Rule* rule , QWidget* parent = 0, const char* name = 0, bool modal = FALSE, WFlags fl = 0);
    ~ConfiguratorDialog();

	Category_List_View *category_list_view_;
	Help_View *help_view_;
	Options_View *options_view_;
    QFrame* Frame4;
    QPushButton* create_button_;
    QPushButton* close_button_;

	set_categories(Option_Category* root);
	set_category(Option_Category* category, Category_List_Item* this_item);
	
protected slots:
	void create_svc_conf();

protected:
    QGridLayout* ConfiguratorDialogLayout;
    QHBoxLayout* Frame4Layout;
    QHBoxLayout* Layout2;

private:
	Rule* rule_;
	Option_Category* root_;
};

#endif // _CONFIGURATORDIALOG_H_
