
#ifndef SENDER_THREE_PORT_IDL
#define SENDER_THREE_PORT_IDL

#include <Components.idl>
#include "cuts/CUTS.idl"
#include "Sender.idl"

component Sender_Three_Port
{
  consumes Dummy_Event input_two;
  
  consumes Dummy_Event input_three;
  
  consumes Dummy_Event input;
  
  emits Dummy_Event output_three;
  
  emits Dummy_Event output_two;
  
  emits Dummy_Event output;
  
  uses CUTS::Testing_Service cuts_testing_service;
};

home Sender_Three_Port_Factory
  manages Sender_Three_Port
{
};

#endif // SENDER_THREE_PORT_IDL

