
#ifndef SENDER_FOUR_PORT_IDL
#define SENDER_FOUR_PORT_IDL

#include <Components.idl>
#include "cuts/CUTS.idl"
#include "Sender.idl"

component Sender_Four_Port
{
  emits Dummy_Event output_four;
  
  emits Dummy_Event output_three;
  
  consumes Dummy_Event input_four;
  
  consumes Dummy_Event input;
  
  consumes Dummy_Event input_three;
  
  consumes Dummy_Event input_two;
  
  uses CUTS::Testing_Service cuts_testing_service;
  
  emits Dummy_Event output_two;
  
  emits Dummy_Event output;
};

home Sender_Four_Port_Factory
  manages Sender_Four_Port
{
};

#endif // SENDER_FOUR_PORT_IDL

