
#ifndef SENDER_TWO_PORT_IDL
#define SENDER_TWO_PORT_IDL

#include <Components.idl>
#include "cuts/CUTS.idl"
#include "Sender.idl"

component Sender_Two_Port
{
  consumes Dummy_Event input_two;
  
  consumes Dummy_Event input;
  
  emits Dummy_Event output;
  
  emits Dummy_Event output_two;
  
  uses CUTS::Testing_Service cuts_testing_service;
};

home Sender_Two_Port_Factory
  manages Sender_Two_Port
{
};

#endif // SENDER_TWO_PORT_IDL

