// -*- C++ -*-

// This file was generated by
// $Id$

#ifndef _SENDER_THREE_PORT_COWORKER_H_
#define _SENDER_THREE_PORT_COWORKER_H_

#include /**/ "ace/pre.h"

#include "cuts/CUTS_exec_export.h"
#include "Sender_Three_Port_svnt.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/LocalObject.h"
#include "cuts/config.h"
#include "cuts/CCM_CoWorkEr_T.h"
#include "cuts/PortAgent.h"
#include "cuts/EventHandler_T.h"
#include "cuts/CCM_Event_Producer_T.h"
namespace CIDL_Sender_Three_Port_Impl 
{
  class CUTS_EXEC_Export Sender_Three_Port_CoWorkEr :
  	public CUTS_CCM_CoWorkEr_T <Sender_Three_Port_Exec, Sender_Three_Port_Context>,
  	public virtual TAO_Local_RefCounted_Object 
  {
    public:
    /// Type definition for this CoWorkEr.
    typedef CUTS_CCM_CoWorkEr_T <
    	Sender_Three_Port_Exec, Sender_Three_Port_Context> CoWorkEr_Type;

    // Constructor
    Sender_Three_Port_CoWorkEr (void);

    // Destructor
    virtual ~Sender_Three_Port_CoWorkEr (void);

    /// Event Sink: input_two
    virtual void push_input_two (
      Dummy_Event * ev
      ACE_ENV_ARG_DECL_WITH_DEFAULTS)
    	ACE_THROW_SPEC ((::CORBA::SystemException));

    /// Event Sink: input
    virtual void push_input (
      Dummy_Event * ev
      ACE_ENV_ARG_DECL_WITH_DEFAULTS)
    	ACE_THROW_SPEC ((::CORBA::SystemException));

    /// Event Sink: input_three
    virtual void push_input_three (
      Dummy_Event * ev
      ACE_ENV_ARG_DECL_WITH_DEFAULTS)
    	ACE_THROW_SPEC ((::CORBA::SystemException));

    // Environment: activate
    void cuts_activate (void);

    // SessionComponent: set_session_context
    void set_session_context (
      ::Components::SessionContext_ptr ctx
      ACE_ENV_ARG_DECL_WITH_DEFAULTS)
      ACE_THROW_SPEC ((::CORBA::SystemException,
                       ::Components::CCMException));

    // SessionComponent: ciao_preactivate
    void ciao_preactivate (
      ACE_ENV_SINGLE_ARG_DECL_WITH_DEFAULTS)
      ACE_THROW_SPEC ((::CORBA::SystemException,
                       ::Components::CCMException));

    // SessionComponent: ccm_activate
    void ccm_activate (
      ACE_ENV_SINGLE_ARG_DECL_WITH_DEFAULTS)
      ACE_THROW_SPEC ((::CORBA::SystemException,
                       ::Components::CCMException));

    // SessionComponent: ciao_postactivate
    void ciao_postactivate (
      ACE_ENV_SINGLE_ARG_DECL_WITH_DEFAULTS)
      ACE_THROW_SPEC ((::CORBA::SystemException,
                       ::Components::CCMException));

    // SessionComponent: ccm_passivate
    void ccm_passivate (
      ACE_ENV_SINGLE_ARG_DECL_WITH_DEFAULTS)
      ACE_THROW_SPEC ((::CORBA::SystemException,
                       ::Components::CCMException));

    // SessionComponent: ccm_remove
    void ccm_remove (
      ACE_ENV_SINGLE_ARG_DECL_WITH_DEFAULTS)
      ACE_THROW_SPEC ((::CORBA::SystemException,
                       ::Components::CCMException));

    private:
    // Initializer helper method
    void init (void);

    // Finalizer helper method
    void fini (void);

    // Type definition for event handlers.
    typedef CUTS_Event_Handler_T <
      Sender_Three_Port_CoWorkEr> Event_Handler_Type;

    void push_input_event_handler (CUTS_Activation_Record * record);
    CUTS_Port_Agent push_input_port_agent_;
    Event_Handler_Type push_input_event_handler_;

    void push_input_three_event_handler (CUTS_Activation_Record * record);
    CUTS_Port_Agent push_input_three_port_agent_;
    Event_Handler_Type push_input_three_event_handler_;

    void push_input_two_event_handler (CUTS_Activation_Record * record);
    CUTS_Port_Agent push_input_two_port_agent_;
    Event_Handler_Type push_input_two_event_handler_;

    // Type definition for the event producer.
    typedef CUTS_CCM_Event_Producer_T <
      Sender_Three_Port_Context> Event_Producer;

    Event_Producer event_producer_;
  };

  class CUTS_EXEC_Export Sender_Three_Port_Factory_CoWorkEr_Factory :
    virtual public Sender_Three_PortHome_Exec,
  	virtual public TAO_Local_RefCounted_Object 
  {
    public:
    Sender_Three_Port_Factory_CoWorkEr_Factory (void);
    virtual ~Sender_Three_Port_Factory_CoWorkEr_Factory (void);

    virtual ::Components::EnterpriseComponent_ptr create (ACE_ENV_SINGLE_ARG_DECL_WITH_DEFAULTS)
    ACE_THROW_SPEC ((::CORBA::SystemException, ::Components::CCMException));
  };

  extern "C" CUTS_EXEC_Export ::Components::HomeExecutorBase_ptr
  create_Sender_Three_Port_Factory_CoWorkEr_Factory_Impl (void);
}

#include /**/ "ace/post.h"

#endif  // !defined _SENDER_THREE_PORT_COWORKER_H_
