//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.07.10 at 10:44:21 PM EDT 
//


package edu.vanderbilt.isis.gme.xme;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import edu.vanderbilt.isis.gme.xme.Atom;
import edu.vanderbilt.isis.gme.xme.Attribute;
import edu.vanderbilt.isis.gme.xme.Connection;
import edu.vanderbilt.isis.gme.xme.Constraint;
import edu.vanderbilt.isis.gme.xme.Model;
import edu.vanderbilt.isis.gme.xme.Name;
import edu.vanderbilt.isis.gme.xme.Reference;
import edu.vanderbilt.isis.gme.xme.Regnode;
import edu.vanderbilt.isis.gme.xme.Set;


/**
 * <p>Java class for model element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="model">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}name"/>
 *           &lt;choice>
 *             &lt;element ref="{}regnode"/>
 *             &lt;element ref="{}constraint"/>
 *             &lt;element ref="{}attribute"/>
 *             &lt;element ref="{}model"/>
 *             &lt;element ref="{}atom"/>
 *             &lt;element ref="{}reference"/>
 *             &lt;element ref="{}set"/>
 *             &lt;element ref="{}connection"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *         &lt;attribute name="childrelidcntr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="derivedfrom" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *         &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *         &lt;attribute name="isinstance" default="no">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="yes"/>
 *               &lt;enumeration value="no"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *         &lt;attribute name="isprimary" default="yes">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="yes"/>
 *               &lt;enumeration value="no"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *         &lt;attribute name="kind" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *         &lt;attribute name="perm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="relid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="role" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(AccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "regnode",
    "constraint",
    "attribute",
    "model",
    "atom",
    "reference",
    "set",
    "connection"
})
@XmlRootElement(name = "model")
public class Model {

    protected Name name;
    protected Regnode regnode;
    protected Constraint constraint;
    protected Attribute attribute;
    protected Model model;
    protected Atom atom;
    protected Reference reference;
    protected Set set;
    protected Connection connection;
    @XmlAttribute
    protected String childrelidcntr;
    @XmlAttribute
    @XmlIDREF
    protected Object derivedfrom;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isinstance;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isprimary;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String kind;
    @XmlAttribute
    protected String perm;
    @XmlAttribute
    protected String relid;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String role;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the regnode property.
     * 
     * @return
     *     possible object is
     *     {@link Regnode }
     *     
     */
    public Regnode getRegnode() {
        return regnode;
    }

    /**
     * Sets the value of the regnode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Regnode }
     *     
     */
    public void setRegnode(Regnode value) {
        this.regnode = value;
    }

    /**
     * Gets the value of the constraint property.
     * 
     * @return
     *     possible object is
     *     {@link Constraint }
     *     
     */
    public Constraint getConstraint() {
        return constraint;
    }

    /**
     * Sets the value of the constraint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Constraint }
     *     
     */
    public void setConstraint(Constraint value) {
        this.constraint = value;
    }

    /**
     * Gets the value of the attribute property.
     * 
     * @return
     *     possible object is
     *     {@link Attribute }
     *     
     */
    public Attribute getAttribute() {
        return attribute;
    }

    /**
     * Sets the value of the attribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attribute }
     *     
     */
    public void setAttribute(Attribute value) {
        this.attribute = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link Model }
     *     
     */
    public Model getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link Model }
     *     
     */
    public void setModel(Model value) {
        this.model = value;
    }

    /**
     * Gets the value of the atom property.
     * 
     * @return
     *     possible object is
     *     {@link Atom }
     *     
     */
    public Atom getAtom() {
        return atom;
    }

    /**
     * Sets the value of the atom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Atom }
     *     
     */
    public void setAtom(Atom value) {
        this.atom = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setReference(Reference value) {
        this.reference = value;
    }

    /**
     * Gets the value of the set property.
     * 
     * @return
     *     possible object is
     *     {@link Set }
     *     
     */
    public Set getSet() {
        return set;
    }

    /**
     * Sets the value of the set property.
     * 
     * @param value
     *     allowed object is
     *     {@link Set }
     *     
     */
    public void setSet(Set value) {
        this.set = value;
    }

    /**
     * Gets the value of the connection property.
     * 
     * @return
     *     possible object is
     *     {@link Connection }
     *     
     */
    public Connection getConnection() {
        return connection;
    }

    /**
     * Sets the value of the connection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Connection }
     *     
     */
    public void setConnection(Connection value) {
        this.connection = value;
    }

    /**
     * Gets the value of the childrelidcntr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildrelidcntr() {
        return childrelidcntr;
    }

    /**
     * Sets the value of the childrelidcntr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildrelidcntr(String value) {
        this.childrelidcntr = value;
    }

    /**
     * Gets the value of the derivedfrom property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDerivedfrom() {
        return derivedfrom;
    }

    /**
     * Sets the value of the derivedfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDerivedfrom(Object value) {
        this.derivedfrom = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the isinstance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsinstance() {
        if (isinstance == null) {
            return "no";
        } else {
            return isinstance;
        }
    }

    /**
     * Sets the value of the isinstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsinstance(String value) {
        this.isinstance = value;
    }

    /**
     * Gets the value of the isprimary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsprimary() {
        if (isprimary == null) {
            return "yes";
        } else {
            return isprimary;
        }
    }

    /**
     * Sets the value of the isprimary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsprimary(String value) {
        this.isprimary = value;
    }

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKind(String value) {
        this.kind = value;
    }

    /**
     * Gets the value of the perm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerm() {
        return perm;
    }

    /**
     * Sets the value of the perm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerm(String value) {
        this.perm = value;
    }

    /**
     * Gets the value of the relid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelid() {
        return relid;
    }

    /**
     * Sets the value of the relid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelid(String value) {
        this.relid = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

}
