// -*- IDL -*-

//=============================================================================
/**
 * @file      CBMLManager.idl
 *
 * $Id$
 *
 * @author    James H. Hill
 */
//=============================================================================

#ifndef _CBML_MANAGER_IDL_
#define _CBML_MANAGER_IDL_

#include <Gme.idl>
#include <Core.idl>

[
  uuid(9289091B-ECBE-4934-B631-E3F69F3940C0),
  version(1.0),
]
library CBMLManager_AddonLib
{
  importlib("stdole32.tlb");

  [uuid (FC3DDE48-DD56-4F65-87DD-7DE9A262CEDC)]
  coclass CBMLManager_Addon
  {
    [default] interface IMgaComponentEx;
    interface IMgaComponent;
    interface IGMEVersionInfo;
  };
};

#endif

