/* -*- IDL -*- */

//=============================================================================
/**
 * @file      Node_Daemon.idl
 *
 * $Id$
 *
 * @author    James H. Hill
 */
//=============================================================================

#ifndef _CUTS_NODE_DAEMON_IDL_
#define _CUTS_NODE_DAEMON_IDL_

module CUTS
{
  /// Type definition of the property string list.
  typedef sequence <string> Properties;

  struct Node_Binding
  {
    boolean localhost;

    unsigned short port;
  };

  struct Node_Task
  {
    /// Human readable name of the task.
    string name;

    /// Executable name of the task.
    string execname;

    /// The arguments for the task.
    string arguments;
  };

  /**
   * @class Task_Manager
   *
   * Task manager interface for the node daemon. This allows client
   * to control the spawning/killing of child processes on the
   * hosting node.
   */
  interface Task_Manager
  {
    /**
     * Spawn a new task in the task manager. The task is spawned
     * immediately and runs infinitely or to completion.
     *
     * @param[in]       task      Target task to spawn.
     * @retval          -1        The task failed to spawn.
     * @retval          0         Failed to spawn the task.
     */
    unsigned long spawn_task (in Node_Task task);

    /**
     * Kill an existing task. If the task exist in the task manager,
     * then it will receive the SIGINT signal. Otherwise, this method
     * has no side effects.
     *
     * @param[in]     name        Name of the task.
     * @retval        -1          The task failed to spawn.
     * @retval        0           Failed to spawn the task.
     */
    unsigned long kill_task (in string name);

    /// Shutdown the task manager.
    oneway void shutdown ();
  };
};

#endif  /* !defined _CUTS_NODE_DAEMON_IDL_ */
