// -*- IDL -*-

//=============================================================================
/**
 * @file      ComponentLib.idl
 *
 * $Id$
 *
 * [insert description here]
 *
 * $Id$
 */
//=============================================================================

#ifndef _GME_BON_COMPONENTLIB_IDL_
#define _GME_BON_COMPONENTLIB_IDL_

#include "InterfaceColl.h"
#include "meta.idl"
#include "mga.idl"
#include "mgautil.idl"
#include "gme.idl"
#include "parser.idl"

#endif  // !defined _GME_BON_COMPONENTLIB_IDL_
