// $Id: $

// ============================================================================
//
// = LIBRARY
//    PICML/tests/IDL_to_PICML
//
// = FILENAME
//    Union.idl
//
// = DESCRIPTION
//    This file contains examples of IDL code that test
//    union types
//
// = AUTHORS
//    Harold Owens II <owensh@cs.iupui.edu>
//
// ============================================================================

#ifndef _UNION_IDL_
#define _UNION_IDL_

module UnionNoun
{
  enum eNoun
  {
    E_PERSON, E_PLACE, E_THING, E_EVENT, E_IDEA
  };

  struct Person
  {
    string  m_name;
    float   m_height;
    short   m_age;
  };

  struct Place
  {
    string  m_name_of;
    long    m_how_many;
    boolean m_is_real;
  };

  struct Thing
  {
    string  m_name;
    long    m_number_of;
  };

  struct Event
  {
    string  m_name;
    boolean m_present;
    long    m_id;
    short   m_type;
  };

  struct Idea
  {
    string  m_name;
    boolean m_is_great;
    long    m_id;
    char    m_begin_letter;
  };

  union MixedSelection switch (eNoun)
  {
    case E_PERSON:  Person a_person;
    case E_PLACE:   Place  a_place;
    case E_THING:   Thing  a_thing;
    case E_EVENT:   Event  an_event;
    case E_IDEA:    Idea   an_idea;
  };
};

#endif
