// -*- C++ -*-

//=============================================================================
/**
 *  @file         Model_Intelligence.idl
 *
 * $Id: Model_Intelligence.idl 2839 2012-02-11 18:59:36Z hillj $
 *
 * @author        Tanumoy Pati
 */
//=============================================================================

#ifndef _MODEL_INTELLIGENCE_IDL_
#define _MODEL_INTELLIGENCE_IDL_

#include <Gme.idl>
#include <Core.idl>

[
  uuid(0913924c-6bda-4966-84c1-dc3eedb36ac9),
  version(1.0),
]
library Model_Intelligence_AddonLib
{
  importlib("stdole32.tlb");

  [uuid (21d9dfcc-4568-48d8-874a-9683fb21409d)]
  coclass Model_Intelligence_Addon
  {
    [default] interface IMgaComponentEx;
    interface IMgaComponent;
    interface IGMEVersionInfo;
  };
};

#endif

