#ifndef _CUTS_BENCHMARK_AGENT_IDL_
#define _CUTS_BENCHMARK_AGENT_IDL_

#include "cuts/performance.idl"

module CUTS
{
  interface Benchmark_Agent
  {
    /// Get the performance data from the agent.
    Benchmark_Data performance_data ();
  };
};

#endif  // !defined _CUTS_BENCHMARK_AGENT_IDL_
