// -*- IDL -*-

//=============================================================================
/**
 * @file      events.idl
 *
 * $Id$
 *
 * @author    James H. Hill <hillj@isis.vanderbilt.edu>
 */
//=============================================================================

#ifndef _CUTS_EVENTS_IDL_
#define _CUTS_EVENTS_IDL_

#include <Components.idl>

module CUTS
{
  /**
   * Dummy event with no payload. This event can serve as a placeholder
   * during emulation until more is learned about the event types.
   */
  eventtype Empty_Event { };

  /**
   * Dummy event with a payload. It allows experiments to transmit events
   * with dummy data associated with it. This event can serve as a placeholder
   * during emulation until more is learned about the event types.
   */
  eventtype Payload_Event
  {
    /// Size of the events payload.
    public long size;

    /// The payload for the event.
    public string payload;
  };
};

#endif  // !defined _CUTS_EVENTS_IDL_
