// ============================================================================
//
// = LIBRARY
//    PICML/tests/IDL_to_PICML
//
// = FILENAME
//    Constants.idl
//
// = DESCRIPTION
//    This file contains examples of IDL code that test
//    basic types MAX and MIN boundaries.
//
// = AUTHORS
//    James H. Hill <hillj@cs.iupui.edu>
//    Harold Owens II <owensh@cs.iupui.edu>
//
// ============================================================================

#ifndef _CONSTANT_IDL_
#define _CONSTANT_IDL_

// boolean types
const boolean CONST_TRUE = TRUE;
const boolean CONST_FALSE = FALSE;

// integer types
const short CONST_SHORT_MIN = -32768;
const short CONST_SHORT_MAX = 32767;
const unsigned short CONST_UNSIGNED_SHORT_MAX = 65535;

const long CONST_LONG_MIN = -2147483648;
const long CONST_LONG_MAX = 2147483647;
const unsigned long CONST_UNSIGNED_LONG_MAX = 4294967295;

const long long CONST_LONG_LONG_MIN = -9223372036854775808;
const long long CONST_LONG_LONG_MAX = 9223372036854775807;
const unsigned long long CONST_UNSIGNED_LONG_LONG_MAX = 18446744073709551615;

// float types
const float CONST_FLOAT_MIN = 1.175494351e-38F;
const float CONST_FLOAT_MAX = 3.402823466e+38F;

// double types
const double CONST_DOUBLE_MIN = 2.225073858507202e-308;
const double CONST_DOUBLE_MAX = 1.797693134862315e+308;

// char types
const char CONST_CHAR_MIN = 'a';
const char CONST_CHAR_MAX = 'Z';

#endif
