// ============================================================================
//
// = LIBRARY
//    PICML/tests/IDL_to_PICML
//
// = FILENAME
//    Typedef.idl
//
// = DESCRIPTION
//    This file contains examples of IDL code that test
//    typedef of basic and complex types
//
// = AUTHORS
//    Harold Owens II <owensh@cs.iupui.edu>
//
// ============================================================================

#ifndef _TYPEDEF_IDL_
#define _TYPEDEF_IDL_

module Noun
{
  struct Person
  {
    string  m_name;
    float   m_height;
    short   m_age;
  };

  struct Place
  {
    string  m_name_of;
    long    m_how_many;
    boolean m_is_real;
  };

  struct Thing
  {
    string  m_name;
    long    m_number_of;
  };

  struct Event
  {
    string  m_name;
    boolean m_present;
    long    m_id;
    short   m_type;
  };

  struct Idea
  {
    string  m_name;
    boolean m_is_great;
    long    m_id;
    char    m_begin_letter;
  };

  interface emptyNoun
  {
  };

  // const modifier
  const short aShortConstant = 5;
  const long  aLongConstant = 2;

  // typedef complex types
  typedef Person personArray[aShortConstant];
  typedef Place  placeArray[aShortConstant];
  typedef Thing  thingArray[aShortConstant];
  typedef Event  eventArray[aShortConstant];
  typedef Idea   ideaArray[aShortConstant];
  typedef emptyNoun emptyNounArray[aShortConstant];

  // typedef basic types
  typedef long longArray[aLongConstant][aLongConstant];
  typedef short shortArray[aLongConstant][aLongConstant];
  typedef double doubleArray[aLongConstant][aLongConstant];
  typedef float floatArray[aLongConstant][aLongConstant];
  typedef boolean booleanArray[aLongConstant][aLongConstant];
  typedef char charArray[aLongConstant][aLongConstant];
};

#endif
